[project]
name = "ultimatevocalremovergui"
version = "5.7.0"
description = "GUI for a Vocal Remover that uses Deep Neural Networks."
readme = "README.md"
requires-python = ">=3.9, <3.10"
dependencies = [
    "audioread>=3.0.1",
    "cryptography>=45.0.3",
    "diffq>=0.2.4",
    "einops>=0.8.1",
    "julius>=0.2.7",
    "kthread>=0.2.3",
    "librosa>=0.11.0",
    "matchering>=2.0.6",
    "ml-collections>=0.1.1",
    "natsort>=8.4.0",
    "numpy>=2.0.2",
    "omegaconf>=2.3.0",
    "onnx>=1.18.0",
    "onnx2pytorch>=0.5.1",
    "onnxruntime>=1.19.0",
    "onnxruntime-gpu>=1.19.0",
    "opencv-python>=4.11.0.86",
    "pillow>=9.3.0, <10.0.0",
    "playsound==1.2.2",
    "psutil>=7.0.0",
    "pydub>=0.25.1",
    "pyglet>=2.1.6",
    "pyperclip>=1.9.0",
    "pyrubberband>=0.4.0",
    "pysoundfile>=0.9.0.post1",
    "pytorch-lightning>=2.5.1.post0",
    "pyyaml>=6.0.2",
    "samplerate>=0.2.1",
    "scipy>=1.13.1",
    "screeninfo>=0.8.1",
    "soundfile>=0.13.1",
    "tkinterdnd2>=0.4.3",
    "torch>=2.7.1",
    "wget>=3.2",
]

[tool.ruff]
line-length = 110
